.

diff --git a/cowbuilder-dist b/cowbuilder-dist
--- a/cowbuilder-dist
+++ b/cowbuilder-dist
@@ -12,57 +12,55 @@ if [ -z "$KEY_ID" ]; then
     KEY_ID="4F23A0260F19DAC5"
 fi
 
-if [ -z "$2" ]; then
-    case "$1" in
-        install )
-            sudo apt-get install -y ubuntu-dev-tools cowbuilder debhelper dput
-            mkdir -p ~/pbuilder/hooks ~/pbuilder/local
-            cat >~/pbuilder/hooks/D05local <<EOF
+case "$1" in
+    install )
+        sudo apt-get install -y ubuntu-dev-tools cowbuilder debhelper dput
+        mkdir -p ~/pbuilder/hooks ~/pbuilder/local
+        cat >~/pbuilder/hooks/D05local <<EOF
 #!/bin/sh -e
 if [ -f "$HOME/pbuilder/local/\$DIST/Packages" ]; then
   echo "deb [trusted=yes] file:///$HOME/pbuilder/local/\$DIST ./" | tee /etc/apt/sources.list.d/local.list
   apt-get update -o Dir::Etc::sourcelist="sources.list.d/local.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
 fi
 EOF
-            chmod +x ~/pbuilder/hooks/D05local
-            cat >~/pbuilder/local/update <<EOF
+        chmod +x ~/pbuilder/hooks/D05local
+        cat >~/pbuilder/local/update <<EOF
 #!/bin/sh -e
 for dist in $dists; do
   (cd \$dist && apt-ftparchive packages . >Packages)
 done
 EOF
-            chmod +x ~/pbuilder/local/update
-            cat >~/.pbuilderrc <<EOF
+        chmod +x ~/pbuilder/local/update
+        cat >~/.pbuilderrc <<EOF
 HOOKDIR="$HOME/pbuilder/hooks"
 BINDMOUNTS="$HOME/pbuilder/local"
 EOF
-            exit 0
-            ;;
+        exit 0
+        ;;
 
-        create | update)
-            for dist in $dists; do
-                for arch in $archs; do
+    create | update)
+        for dist in $dists; do
+            for arch in $archs; do
+                echo ""
+                echo ""
+                echo "*******************************************************************************"
+                echo "Doing $1 for distribution $dist arch $arch"
+                echo "*******************************************************************************"
+                echo ""
+                mkdir -p "$HOME/pbuilder/local/$dist"
+                cowbuilder-dist "$dist" "$arch" "$@" || {
                     echo ""
+                    echo "****************************************"
+                    echo "             FAILED $1"
+                    echo "****************************************"
                     echo ""
-                    echo "*******************************************************************************"
-                    echo "Doing $1 for distribution $dist arch $arch"
-                    echo "*******************************************************************************"
-                    echo ""
-                    mkdir -p "$HOME/pbuilder/local/$dist"
-                    cowbuilder-dist "$dist" "$arch" "$@" || {
-                        echo ""
-                        echo "****************************************"
-                        echo "             FAILED $1"
-                        echo "****************************************"
-                        echo ""
-                        exit 2
-                    }
-                done
+                    exit 2
+                }
             done
-            exit 0
-            ;;
-    esac
-fi
+        done
+        exit 0
+        ;;
+esac
 
 for file in $@; do
     case "$file" in
